### ISSUE TITLE
DRTIO link does not come up between Kasli 2.0

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#1570]
# Bug Report

A DRTIO link cannot be established between two Kasli 2.0's.
The master SFP1 and slave SFP0 are connected by fibre transceivers. The master SFP link light turns on, but the satellite link light does not. No DRTIO link is established.

We have tried different transceivers, and different SFP ports on the master. In all cases the behaviour is the same. The SFP0 of the satellite works with an ethernet SFP when the satellite is flashed as a master. This weakly suggests that this is a software / configuration problem rather than a hardware problem.

### Actual (undesired) Behavior

Master core log:
```
...
[  1016.096514s]  INFO(runtime::rtio_mgt::drtio): [LINK#1] link RX became up, pinging
[  1036.252677s] ERROR(runtime::rtio_mgt::drtio): [LINK#1] ping failed
[  1036.458121s]  INFO(runtime::rtio_mgt::drtio): [LINK#1] link RX became up, pinging
[  1056.614272s] ERROR(runtime::rtio_mgt::drtio): [LINK#1] ping failed
[  1056.819602s]  INFO(runtime::rtio_mgt::drtio): [LINK#1] link RX became up, pinging  
```

Satellite core log:
```
Booting from flash...
Starting firmware.
[0.000005s]  INFO(satman): ARTIQ satellite manager starting...
[     0.005612s]  INFO(satman): software ident 6.unknown.beta;lasersatellite   
[     0.012327s]  INFO(satman): gateware ident 6.unknown.beta;lasersatellite    
[     0.365784s]  INFO(board_artiq::si5324): waiting for Si5324 lock...        
[     2.298061s]  INFO(board_artiq::si5324):   ...locked    
```

### Your System (omit irrelevant parts)

* ARTIQ version: based on 3e3883302001eaee5c46ff33726ef16b25537fb7
* Hardware involved: 2x Kasli 2.0

**Comment by cjbe** [comment]
This is possibly related to #1562

**Comment by hartytp** [comment]
Are the transceiver fault indicators still high?

**Comment by cjbe** [comment]
Unknown - I am working remotely, and don't have a readout for that. I understand that at one point @sotirova observed this, but I am not sure with what level of confidence.

**Comment by hartytp** [comment]
It was definitely the case in her setup previously. I’m happy to sketch out some pseudo code to add readout of them if it helps?

**Comment by cjbe** [comment]
Sure - that would be useful (especially if you are happy to close the loop with @sotirova when implementing)

**Comment by jordens** [comment]
Drive TX_DISABLE.
https://github.com/m-labs/artiq/pull/1508

**Comment by hartytp** [comment]
> Drive TX_DISABLE

I'm aware of that issue but don't believe that's the cause of what we're seeing. @sotirova and Fabian measured the voltages on all outputs of the two I2C expanders on the master + satellite. TX_DISABLE is low here, so it's not an issue with the particular transceivers we're using -- although I do agree that this should generally be driven low in the firmware; that's been on by to do list for a while now.

What's interesting is that we do see a TX_FAULT on the master side of the DRTIO link. My understanding (from talking to @sbourdeauducq is that this indicates an internal fault with the transceiver) so I assumed it was just a faulty transceiver. However, @cjbe reports having tried multiple transceivers without success, so that's maybe less likely. It feels worth reporting the state of TX_DISABLE when we get failed pings. Again, that's a PR that's been on my to do list for some time.

![image](https://user-images.githubusercontent.com/21218399/102713764-632e4f00-42c2-11eb-9ef1-0f5f89bc2c70.png)

![image](https://user-images.githubusercontent.com/21218399/102713770-6a555d00-42c2-11eb-94f0-0e5353c23c6c.png)

![image](https://user-images.githubusercontent.com/21218399/102713774-70e3d480-42c2-11eb-8f02-8bbfd8c37d73.png)
![image](https://user-images.githubusercontent.com/21218399/102713776-73dec500-42c2-11eb-965a-2fd55f53ac4f.png)
![image](https://user-images.githubusercontent.com/21218399/102713785-7b05d300-42c2-11eb-9e7f-e6d375e2d124.png)

> or use a DAC.

Can you elaborate on that, I don't follow. Which DAC do you mean?

**Comment by hartytp** [comment]
doh, nope, I've just made a transcription error in the above. Master SFP1 TX_DISABLE is IC25 pin 2 which should be at 0V but is at 2V0. So the fix is just to extend Pawel's patch to drive it low.

**Comment by jordens** [comment]
DAC as in direct attach cable.
