### ISSUE TITLE
ERROR LED cannot be properly controlled on EFC

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#2205]

**Comment by occheung** [comment]
The I/O expander `init()` invocation is missing. This should explain why the proposal in #2201 actually causes a behavioral difference.

Note that there are no changes to port A output level unless the virtual LED is updated, or the firmware panics. `service()` only emits I2C commands when there are output level changes to ports. Therefore, the I/O expander retains the same output logic level across reboot.

The `init()` was omitted probably due to the board not selecting the correct default clock source. As agreed, later iterations of the EFC card will allow clock selection control via a DIP switch.

A PR to add back the `init()` will follow.
