### ISSUE TITLE
fix qt6 applet embedding on Wayland

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#2513]

**Comment by Spaqin** [comment]
The issue with Wayland is that it doesn't let window embed other foreign windows, and that's not something that can have an easy workaround. For one solution would be to implement a Wayland compositor to replace the dashboard. That would give more control over windows, including foreign applets. Generally it would entail a lot of effort, and it's not a problem on Windows or X11 already.

In this case we could enable Wayland for ``artiq_browser`` since it seems to be working fine (by adding ``-platform wayland;xcb;windows``), and keep the dashboard with xcb/windows only. Since the dashboard would be usable with Wayland _besides_ applets, it could be an optional argument to enable it, with the obvious caveat.

**Comment by Spaqin** [comment]
Only two options to choose the platform on QT:
* we can either ``export QT_QPA_PLATFORM=xcb`` in flake.nix (but need to define the default shell), but this wouldn't work with users who don't use flakes on Linux. You mentioned it not working for you in the original PR, but 
* or we detect the OS in the GUI apps artiq_browser, artiq_dashboard and pass ``-platform xcb`` to QApplication if it's Linux (or not Windows).

**Comment by thomasfire** [comment]
> * Linux (or not Windows).

Maybe, there is some way to detect wayland directly? Other OSes may also do not use it

**Comment by Spaqin** [comment]
> > * Linux (or not Windows).
> 
> Maybe, there is some way to detect wayland directly? Other OSes may also do not use it

Maybe that would be better. Can check if ``QT_QPA_PLUGIN`` was set (need to check which option takes precedence though), and the default platform.
