### ISSUE TITLE
add serial port on win7-experimental VM

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#358]
This blocks #279.

**Comment by whitequark** [comment]
Done. I made QEMU allocate a PTY, since that looks the most like a serial port. Unfortunately there is no good way to figure out *which* PTY it is. Currently it is `/dev/pts/8`. I suggest simply restarting the VM using `xl destroy && xl create` every time you forget which PTY it was attached to.

Alternatively I can attach it to a named pipe, but that's more likely to break software connecting to the virtual serial port. E.g. I don't actually know how to connect a terminal emulator to one.
