### ISSUE TITLE
Wrap error messages in GUI log window

### ISSUE THREAD

**Issue by dleibrandt** [m-labs/artiq#399]
Currently, I have to copy the error messages out of the log window and paste them into a text editor in order to read them, because the lines are much wider than the log window (see error message in #398).  I'd suggest that either the error messages be wrapped or a horizontal scroll bar should be added to the GUI log window.

**Comment by sbourdeauducq** [comment]
For a scrollbar, you can resize the column beyond the window boundary. Clumsy, but that's all Qt has to offer.

Wrapping cannot be done because Qt is absolutely lousy with table/tree layout bugs. Same with adding an option to resize the column from the current contents.

Note that the master also writes logs to its console, and to a file if you run it with ``--log-file``.
