### ISSUE TITLE
AttributeError when setting argument of SPI device

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#493]
Using 1.1 on Windows, we have the following SPI device.

```
 "spi_dds0": {
        "type": "local",
        "module": "artiq.coredevice.ad9914_spi",
        "class": "AD9914_SPI",
        "arguments": {"spi_device": "spi0", "sysclk": 2.4e9, "ioup_device": "ttl38",
                        "cs2_device": "ttl36", "reset_device": "ttl37", "ps0_device": "ttl28",
                        "ps1_device": "ttl29", "ps2_device": "ttl30", "channel": 0}
```

Trying to test this experiment, I have the following build,

```python
class AD9914test(EnvExperiment):


    def build(self):
        self.setattr_device("core")
        self.dds0 = self.get_device("spi_dds0")
        self.setattr_argument("channel", NumberValue(0, ndecimals=0,step=1))
        self.dds0.channel = self.channel
```

When I scan the repository head, I get the error,

```
ERROR:worker(scan,ad9914_spi.py):root:Terminating with exception (AttributeError
: 'NoneType' object has no attribute 'channel')
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-2016-06-24\lib\site-packages\artiq\master\worker
_impl.py", line 241, in main
    examine(ExamineDeviceMgr, ParentDatasetDB, obj["file"])
  File "C:\Anaconda3\envs\artiq-2016-06-24\lib\site-packages\artiq\master\worker
_impl.py", line 144, in examine
    enable_processors=True)
  File "C:\Anaconda3\envs\artiq-2016-06-24\lib\site-packages\artiq\language\envi
ronment.py", line 169, in __init__
    self.build()
  File "c:\artiq-magtrap\repository\test\ad9914_spi.py", line 13, in build
    self.dds0.channel = self.channel
AttributeError: 'NoneType' object has no attribute 'channel'
```

However, if I comment out the the last line `self.dds0.channel = self.channel`, scan the repository head, uncomment the line and then run the experiment, it runs as it should. How should I avoid the initial attribute error?

**Comment by sbourdeauducq** [comment]
During repository scan, devices are not available and all ``get_device`` calls return ``None``. If you really must have devices configured by arguments instead of the device database, simply skip the device interaction in ``build`` if the device is ``None``.

Note that rewriting arguments after the device is created may not work correctly with all drivers; if you really cannot use what the device database system provides you, consider creating the device driver yourself (``from artiq.coredevice.ad9914_spi import AD9914_SPI``, ``self.device = AD9914_SPI(...)``).
