### ISSUE TITLE
Include check_pause in Pauses section of Management System 

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#522]
It could be useful to have a description of `check_pause` included in the Pauses section,

https://m-labs.hk/artiq/manual-master/management_system.html?highlight=pause

**Comment by jordens** [comment]
We do expect that you look around and easily find https://m-labs.hk/artiq/manual-master/management_system.html?highlight=pause#artiq.master.scheduler.Scheduler.check_pause Did you find that?
The API documentation needs to be thorough since it is authoritative and much easier to maintain. Overview and tutorial chapters don't need to be and should not be comprehensive.

**Comment by r-srinivas** [comment]
I did see that. It just seemed that this section was unchanged from the release version, though the pause functionality has changed quite a bit with the inclusion of check_pause. I thought it's useful to perhaps just mention that such a function exists in that section so people can be aware of it.

**Comment by jordens** [comment]
Ok.

**Comment by r-srinivas** [comment]
Thanks.
