### ISSUE TITLE
Reading Inputs and Processing them with Pipistrello

### ISSUE THREAD

**Issue by StanleyEDavidsdavid30** [m-labs/artiq#702]
Hello!

I have a arbitrary function generator which I have connected to pins on Pipistrello. I am generating a square wave with the arbitrary function generator and am trying to use Pipistrello to count the number of rising edges in the square wave. 

I am new to ARTIQ so I am wondering if anyone had any suggestions on how to begin doing this. 

Thanks!

**Comment by jordens** [comment]
Please ask this on the mailing list so that other users can help you. This issue tracker is not meant to be a users' help forum.

To allow someone to help you there, you should describe how you have applied the information from the manual, the information from the API reference, and the examples that you find in ARTIQ. Then describe how far you got. Provide code that you attempted to use.
